import {test} from 'node:test';
import assert from 'node:assert/strict';
import {inspectLog,logReport,MAX_LOG_BYTES} from './logs.mjs';
const header='HP Tuners CSV Log File\nVersion: 1.0\n\n[Log Information]\nNotes: synthetic fixture\n\n[Channel Information]\n0,1,2\nOffset,"Sensor, test",State\ns,V,\n\n[Channel Data]\n';
const data='-0.1,0,Ready\n0,,\n0,2.5,"A ""quoted"" state"\n1,NaN,Ready\n';
test('sparse rows preserve zero, blanks, text and duplicate times without interpolation',()=>{const r=inspectLog(header+data);assert.equal(r.rowCount,4);assert.deepEqual(r.time,{unit:'s',first:-0.1,last:1,span:1.1,duplicateTimes:1});assert.deepEqual(r.channels[1],{id:'1',name:'Sensor, test',unit:'V',numericCount:2,textCount:1,missingCount:1,min:0,max:2.5});});
test('reject ambiguous formats, units, rows and time resets',()=>{for(const text of [header.replace('Version: 1.0','Version: 2.0')+data,header.replace('s,V,','ms,V,')+data,header.replace('0,1,2','0,1,1')+data,header+'1,2\n',header+'NaN,2,Ready\n',header+'1,2,Ready\n0,3,Ready\n',header,header+'0,2,"unfinished'])assert.throws(()=>inspectLog(text));});
test('quoted newlines and CRLF are parsed; nonfinite values never enter ranges',()=>{const r=inspectLog((header+'0,Infinity,"line\none"\n1,-2,Ok\n').replaceAll('\n','\r\n'));assert.equal(r.channels[1].min,-2);assert.equal(r.channels[1].textCount,1);assert.equal(r.channels[2].textCount,2);});
test('bounded imports reject excess bytes and fields',()=>{assert.throws(()=>inspectLog(' '.repeat(MAX_LOG_BYTES+1)));assert.throws(()=>inspectLog(header+'0,1,'+'x'.repeat(4097)));});
test('report provenance and calibration association never authorize learning',async()=>{const raw=header+data;const a=await logReport(raw,'test.csv');assert.equal(a.calibration.sha256,null);assert.equal(a.learningReady,false);assert.equal(a.automaticApplication,false);assert.match(a.source.textSha256,/^[a-f0-9]{64}$/);const b=await logReport(raw,'test.csv','A'.repeat(64),'Operator confirmed');assert.equal(b.calibration.sha256,'a'.repeat(64));assert.equal(a.source.textSha256,b.source.textSha256);await assert.rejects(logReport(raw,'test.csv','a'.repeat(64),''));await assert.rejects(logReport(raw,'test.csv','bad','note'));await assert.rejects(logReport(raw,'../test.csv'));});

test('saved channel selections are validated against the source and retain source hash',async()=>{const raw=header.replace('"Sensor, test"','Engine RPM').replace('s,V,','s,rpm,')+data;const r=await logReport(raw,'sample.csv','','',[{role:'RPM',channelId:'1',evidence:'Synthetic reference source'}]);assert.equal(r.channelSelection.entries[0].channelId,'1');assert.equal(r.channelSelection.learningReady,false);assert.match(r.source.textSha256,/^[a-f0-9]{64}$/);await assert.rejects(logReport(header+data,'sample.csv','','',[{role:'RPM',channelId:'1',evidence:'Wrong units and label'}]));});

test('reopening verifies source contents, allows renaming, and reconstructs measurement metadata',async()=>{const {reopenLogReport}=await import('./logs.mjs');const raw=header.replace('"Sensor, test"','Engine RPM').replace('s,V,','s,rpm,')+data;const report=await logReport(raw,'sample.csv','','',[{role:'RPM',channelId:'1',evidence:'Synthetic reference source'}]);report.channels[1].min=999;report.channelSelection.entries[0].name='Forged label';report.channelSelection.entries[0].flags=['FAKE'];report.measurementChecks={learningReady:true};const reopened=await reopenLogReport(JSON.stringify(report),raw,'renamed.csv');assert.equal(reopened.source.name,'renamed.csv');assert.equal(reopened.channels[1].min,0);assert.equal(reopened.channelSelection.entries[0].name,'Engine RPM');assert.deepEqual(reopened.channelSelection.entries[0].flags,['NONNUMERIC_VALUES_PRESENT']);assert.equal(reopened.measurementChecks.learningReady,false);await assert.rejects(reopenLogReport(JSON.stringify(report),raw.replace('2.5','3.5'),'sample.csv'),/does not match/);});
test('reopening rejects forged release gates, malformed selections and unsupported hashes',async()=>{const {reopenLogReport,MAX_LOG_REPORT_BYTES}=await import('./logs.mjs');const r=await logReport(header+data,'sample.csv');for(const patch of [{learningReady:true},{automaticApplication:true},{status:'RELEASED'},{source:{...r.source,hashScope:'FILE_BYTES'}},{channelSelection:{...r.channelSelection,entries:[{role:'RPM',channelId:'1',evidence:'wrong source'}]}},{calibration:null}])await assert.rejects(reopenLogReport(JSON.stringify({...r,...patch}),header+data,'sample.csv'));await assert.rejects(reopenLogReport(' '.repeat(MAX_LOG_REPORT_BYTES+1),header+data,'sample.csv'));const old={...r};delete old.channelSelection;assert.equal((await reopenLogReport(JSON.stringify(old),header+data,'sample.csv')).channelSelection.entries.length,0);});
