import {test} from 'node:test';import assert from 'node:assert/strict';
import {measurementChecks,measurementCheckText} from './measurements.mjs';
const channel=(id,name,unit,extra={})=>({id,name,unit,numericCount:4,textCount:0,missingCount:2,min:1,max:2,...extra});
const role=(r,name)=>r.candidates.find(c=>c.role===name);
test('commanded lambda never substitutes for measured; voltage never becomes MAF Hz',()=>{const r=measurementChecks({channels:[channel('1','Equivalence Ratio Commanded (SAE)','λ'),channel('2','Mass Airflow Sensor','V',{min:0,max:0}),channel('3','Timing Advance (SAE)','°')]});assert.equal(role(r,'COMMANDED_LAMBDA').status,'CANDIDATE_ONLY');assert.equal(role(r,'MEASURED_LAMBDA').candidates.length,0);assert.equal(role(r,'MAF_FREQUENCY').rejectedUnits[0].unit,'V');assert.equal(role(r,'KNOCK_RETARD').candidates.length,0);assert.equal(r.learningReady,false);assert.equal(r.automaticApplication,false);});
test('duplicate sources stay ambiguous and constant/no-data channels are flagged',()=>{const r=measurementChecks({channels:[channel('1','Engine RPM','rpm'),channel('2','Engine RPM (SAE)','rpm'),channel('3','Intake Air Temp','°F',{min:-83.2,max:-83.2}),channel('4','Wideband Lambda','λ',{numericCount:0,min:null,max:null,textCount:4})]});assert.equal(role(r,'RPM').status,'AMBIGUOUS');assert.deepEqual(role(r,'INTAKE_TEMPERATURE').candidates[0].flags,['CONSTANT_RECORDED_VALUE']);assert.deepEqual(role(r,'MEASURED_LAMBDA').candidates[0].flags,['NO_FINITE_NUMERIC_SAMPLES','NONNUMERIC_VALUES_PRESENT']);assert.match(measurementCheckText(r),/Learning remains blocked/);});
test('unknown labels and units are not guessed; complete candidates never enable correction',()=>{const r=measurementChecks({channels:[channel('1','Wideband Lambda','AFR'),channel('2','Custom Lambda','λ'),channel('3','MAF Frequency','Hz')]});assert.equal(role(r,'MEASURED_LAMBDA').status,'MISSING_OR_UNSUPPORTED_UNIT');assert.equal(role(r,'MAF_FREQUENCY').status,'CANDIDATE_ONLY');assert.equal(r.learningReady,false);});

test('operator mapping requires evidence and current compatible candidate; flags survive',async()=>{const {reviewedMapping}=await import('./measurements.mjs');const i={channels:[channel('1','Engine RPM','rpm',{min:0,max:0}),channel('2','Engine RPM (SAE)','rpm')]};const m=reviewedMapping(i,[{role:'RPM',channelId:'1',evidence:'Synthetic UI test only'}]);assert.equal(m.entries[0].name,'Engine RPM');assert.deepEqual(m.entries[0].flags,['CONSTANT_RECORDED_VALUE']);assert.equal(m.learningReady,false);assert.equal(m.status,'OPERATOR_SELECTED_NOT_SENSOR_VALIDATED');for(const selections of [[{role:'RPM',channelId:'1',evidence:''}],[{role:'RPM',channelId:'stale',evidence:'x'}],[{role:'MAP',channelId:'1',evidence:'x'}],[{role:'RPM',channelId:'1',evidence:'x'},{role:'RPM',channelId:'2',evidence:'x'}]])assert.throws(()=>reviewedMapping(i,selections));assert.throws(()=>reviewedMapping({channels:[channel('1','Engine RPM','rpm',{numericCount:0})]},[{role:'RPM',channelId:'1',evidence:'x'}]));assert.equal(reviewedMapping(i).entries.length,0);});
