import {test} from 'node:test';import assert from 'node:assert/strict';import {channelTimeline} from './timeline.mjs';
const h='HP Tuners CSV Log File\nVersion: 1.0\n\n[Channel Information]\n0,1\nOffset,Engine RPM\ns,rpm\n\n[Channel Data]\n';
test('timeline keeps zero and empty intervals without filling, preserving extrema',()=>{const t=channelTimeline(h+'-1,0\n0,\n1,bad\n2,100\n2,200\n','1');assert.equal(t.bins.length,3);assert.equal(t.bins[0].min,0);assert.equal(t.bins[1].min,null);assert.equal(t.bins[2].min,100);assert.equal(t.bins[2].max,200);assert.equal(t.numericCount,3);assert.equal(t.missingCount,1);assert.equal(t.textCount,1);assert.equal(t.learningReady,false);});
test('zero-duration timestamps share one bin; invalid channel and times are rejected',()=>{const t=channelTimeline(h+'1,8\n1,12\n','1');assert.equal(t.bins.length,1);assert.equal(t.bins[0].max,12);for(const id of ['missing','0'])assert.throws(()=>channelTimeline(h+'0,1\n',id));assert.throws(()=>channelTimeline(h+'0,\n','1'));assert.throws(()=>channelTimeline(h+'2,2\n1,1\n','1'));assert.throws(()=>channelTimeline(h+'-1e308,1\n1e308,2\n','1'));});
test('long recordings are bounded and last timestamp is retained',()=>{const t=channelTimeline(h+'0,1\n9999,5000\n','1');assert.equal(t.bins.length,240);assert.equal(t.bins.at(-1).max,5000);assert.equal(t.bins.reduce((n,b)=>n+b.numericCount,0),2);assert.equal(t.bins.filter(b=>b.min===null).length,238);});
test('selected window excludes outside extrema and includes both endpoint duplicates',()=>{const t=channelTimeline(h+'-1,9000\n0,0\n1,20\n1,30\n2,\n3,40\n3,50\n4,8000\n','1',{start:1,end:3});assert.equal(t.min,20);assert.equal(t.max,50);assert.equal(t.numericCount,4);assert.equal(t.missingCount,1);assert.equal(t.selectedRowCount,5);assert.equal(t.time.duplicateTimes,2);assert.equal(t.recordingTime.first,-1);assert.equal(t.bins.at(-1).max,50);assert.equal(t.automaticApplication,false);});
test('empty and nonnumeric windows retain absence without borrowing neighbors',()=>{const raw=h+'0,100\n1,\n2,bad\n3,900\n';for(const range of [{start:0.2,end:0.8},{start:1,end:2}]){const t=channelTimeline(raw,'1',range);assert.equal(t.min,null);assert.equal(t.max,null);assert.equal(t.numericCount,0);assert.ok(t.bins.every(b=>b.min===null));}const t=channelTimeline(raw,'1',{start:1,end:2});assert.equal(t.missingCount,1);assert.equal(t.textCount,1);});
test('single timestamp view includes all duplicates and full range matches default',()=>{const raw=h+'0,10\n1,20\n1,30\n2,40\n';const t=channelTimeline(raw,'1',{start:1,end:1});assert.equal(t.bins.length,1);assert.equal(t.numericCount,2);assert.equal(t.min,20);assert.equal(t.max,30);assert.deepEqual(channelTimeline(raw,'1',{start:0,end:2}),channelTimeline(raw,'1'));});
test('time windows reject invalid, reversed, or out-of-recording bounds',()=>{const raw=h+'-1,10\n2,40\n';for(const range of [false,[],{}, {start:'0',end:1},{start:NaN,end:1},{start:0,end:Infinity},{start:1,end:0},{start:-2,end:1},{start:0,end:3}])assert.throws(()=>channelTimeline(raw,'1',range));});
