const API_BASE = import.meta.env.VITE_API_BASE_URL || "";

/** Always send cookies so magic-link session works */
export async function apiFetch(path: string, init: RequestInit = {}) {
  const url = API_BASE ? `${API_BASE}${path}` : path;

  // Only default to JSON when the body actually is JSON. FormData must set its
  // own Content-Type, because the multipart boundary is generated by the
  // browser and cannot be written by hand — forcing application/json here made
  // every file upload unparseable by multer.
  const isFormData = typeof FormData !== "undefined" && init.body instanceof FormData;
  const headers = new Headers(init.headers || {});
  if (!isFormData && !headers.has("Content-Type")) {
    headers.set("Content-Type", "application/json");
  }

  const res = await fetch(url, { ...init, credentials: "include", headers });

  if (!res.ok) {
    // Surface the server's message instead of a bare status code.
    let detail = "";
    let errorBody: any;
    try {
      const body = await res.clone().json();
      errorBody = body;
      detail = body?.message ? ` — ${body.message}` : "";
    } catch {
      /* non-JSON error body */
    }
    throw Object.assign(new Error(`HTTP ${res.status}${detail}`), { details: errorBody });
  }
  return res;
}

export async function apiGet<T>(path: string): Promise<T> {
  const res = await apiFetch(path);
  return res.json() as Promise<T>;
}

export async function apiPost<T>(path: string, body: any): Promise<T> {
  const res = await apiFetch(path, { method: "POST", body: JSON.stringify(body) });
  return res.json() as Promise<T>;
}
